### ISSUE TITLE
Define the premises

### ISSUE THREAD

**Issue by kseistrup** [jayliew/religionfusion#1]
Specifically, I feel it's important to define at least two terms here:

### Religion

How does RF define religion?

[Wikipedia reads](https://en.wikipedia.org/wiki/Religion)
> Religion is a cultural system of behaviors and practices, mythologies, world views, sacred texts, holy places, ethics, and societal organisation that relate humanity to what an anthropologist has called “an order of existence”. Different religions may contain various elements, ranging from “the belief in spiritual beings”, the “divine”, “sacred things”, “faith”, a “supernatural being or supernatural beings” such as God or angels, or “…some sort of ultimacy and transcendence that will provide norms and power for the rest of life.”

But as I see it, this will clash with another term that is used in the RF document:

> […] but can't be updated to reflect reality

### Reality

How does RF define reality? In my world something exists in reality if it can be sensed by one or more of the five senses: sight, sensation, hearing, taste, and smell. You could also say that thoughts exist, although the content of the thoughts may not be real (e.g., the thought of a unicorn is real, while the unicorn thought of most likely isn't).

This is important because the documents of RF need be “updated to reflect reality”. I assume most people would say that religion is about something supernatural — let's call is god. But if we cannot see, smell, …, god, can we still say that god is a part of reality? And if god isn't a part of reality, can we say god exists? And if there is no god in reality, is RF a religion or is it just a set of living rules or concepts that tickles our ears?

**Comment by jayliew** [comment]
Great point.

> Aren't you tired of religions that are mostly good, but have some bad parts written 1,000 years ago, but can't be updated to reflect **present day's cultural and societal accepted norms**, because the guy who wrote it declared it as a static global constant? As you can see, this religion is based on a living document. It's on Github, for Jay's sake! (Jay is the guy who started this)
