### ISSUE TITLE
Define “accept other religions”

### ISSUE THREAD

**Issue by kseistrup** [jayliew/religionfusion#2]
The initial paper says

> Other religions are ok, accept them as human beings too. Even atheists.

How is this to be understood? What does accept mean in this context? Obviously, I cannot control what world views other people have, nor should I, and in that sense we can say that accept other religions. However, if my understanding of reality dictates that something be detectable (see #1) in order to exist, obviously I cannot conclude that a divine entity exists, a thus I have to conclude that the claim that a god exists is untrue.

Does RF allow that we call bullshit on religions that claim that one or more divine entities exist (which most religions do, AFAIK), or should we just play along because we're nice?

**Comment by jayliew** [comment]
Excellent point. Bugfix:

> * Other religions are ok, accept them as human beings too. Even atheists.
  * If someone feels very strongly about something about their religion, don't try to convince them otherwise. The promotion of peace and tolerance supercedes logical and scientific correctness.
    * That doesn't mean that you have to give up your own beliefs. You are free to believe anything you want, as well as the other person. Agree to disagree
