### ISSUE TITLE
Refactor reproduction model

### ISSUE THREAD

**Issue by turbomaze** [jayliew/religionfusion#3]
Re: Fscking::"don't do it without protection"

* in short, like a lot of companies, NoSQL is fscking us over
    * NoSQL -> no sequel -> followers of RF cannot have kids
* error rate of common contraceptives is low enough such that achieving the minimum growth rate necessary for a sustainable population is infeasible under the current framework
    * exceptions: ridiculously large amounts of sex, biological immortality
* we can avoid down-rounds in the short-term by expanding into the current population, but once we reach our saturation point, we're in big trouble
* at that point, the population of RF would slowly die off, unable to sustain its numbers through reproduction

To fix these problems, I propose to amend this clause as follows: 

"don't do it without protection... unless you want to"

**Comment by fscking** [comment]
+1

**Comment by jayliew** [comment]
LEGIT. I didn't think of that. Ok, amended as follows

> * By default, you must use protection
  * Unless you and your partner(s) know definitively that none of you have STDs (as verified medically)
