### ISSUE TITLE
Redundant rules

### ISSUE THREAD

**Issue by kseistrup** [jayliew/religionfusion#4]
The two first rules currently says
* Don't kill people
* Killing others to spread or defend RF is totally NOT OK, at all

IMHO the first bullet point is sufficient. If I have already accepted that I shan't kill people, obviously I cannot kill people for the sake of spreading or defending RF.

**Comment by jayliew** [comment]
Fixed. Added a new section about promoting / advocating RF:

> You can talk about RF to others, but do NOT be pushy, or trick them. Per the rule about not allowing killing, killing others to spread or defend RF is totally NOT OK, at all
